import Mathlib

#check norm_sub_sq_real
#check norm_sub_pow_two_real
#check @norm_sub_sq
#check @norm_add_sq
#check norm_add_sq_real
#check real_inner_smul_left
#check real_inner_smul_right
#check inner_sum
#check Finset.sum_smul
#check Finset.sum_sub_distrib
#check Finset.mul_sum
#check Finset.sum_mul
#check inner_sub_left
#check inner_sub_right
#check Finset.sum_nonneg
#check Finset.sum_eq_zero_iff_of_nonneg
#check Finset.exists_le_of_sum_le
#check Finset.exists_lt_of_sum_lt
#check Finset.sum_pos
#check Finset.sum_pos'
#check Finset.sum_lt_sum
#check Finset.sum_le_sum
#check Finset.sum_congr
#check Real.sqrt_le_sqrt
#check sq_le_sq
#check sq_le_sq'
#check pow_le_pow_left
#check sq_nonneg
#check norm_nonneg
