"""LLL-based integer relation search for the minimal polynomial of r_*.

Given r to `digits` decimal places, build the lattice generated by
    (e_i, round(10^digits * r^i))       i = 0..d
and LLL-reduce.  A short vector whose last coordinate is negligibly small
yields integer coefficients (a_0..a_d) with sum a_i r^i ~ 0.
"""
from __future__ import annotations
import json
import sys
import time

import mpmath as mp
from sympy import Matrix, ZZ


def relation(r, d, digits, delta='0.99'):
    mp.mp.dps = digits + 60
    N = mp.mpf(10) ** digits
    rows = []
    for i in range(d + 1):
        row = [0] * (d + 2)
        row[i] = 1
        row[d + 1] = int(mp.nint(N * r ** i))
        rows.append(row)
    M = Matrix(rows)
    t0 = time.time()
    R = M.lll(delta=mp.mpf(delta))
    dt = time.time() - t0
    out = []
    for i in range(R.rows):
        row = [int(x) for x in R.row(i)]
        tail = abs(row[-1])
        # residual in units of r: tail / N
        out.append((tail, row[:-1], tail / float(N) if N < mp.mpf(10) ** 300 else None))
    return out, dt


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else r'E:\study\ADB\runtime\hp_root_1000.json'
    d = int(sys.argv[2]) if len(sys.argv) > 2 else 30
    digits = int(sys.argv[3]) if len(sys.argv) > 3 else 900
    rec = json.load(open(path, encoding='utf-8'))
    mp.mp.dps = digits + 60
    r = mp.mpf(rec['r'])
    t0 = time.time()
    out, dt = relation(r, d, digits)
    print(f'd={d} digits={digits} lll_time={dt:.1f}s total={time.time()-t0:.1f}s')
    out.sort(key=lambda t: t[0])
    for tail, coeffs, _ in out[:4]:
        print('  tail_digits', len(str(tail)), 'coeff_max_digits',
              max(len(str(abs(c))) for c in coeffs), 'coeffs', coeffs)


if __name__ == '__main__':
    main()
